   echo "services:
     - type: web
       name: uaaa-server
       env: node
       plan: free
       buildCommand: npm install
       startCommand: npm start
       rootDir: .
       envVars:
         - key: NODE_ENV
           value: production
         - key: MONGO_URI
           sync: false
         - key: JWT_SECRET
           sync: false
         - key: PORT
           value: 10000" > render.yaml